### ISSUE TITLE
Documentation should be published as a gitbook

### ISSUE THREAD

**Issue by ifiokjr** [kickjump/kj#6]
### Motivation

It should be simple for any developer to find out how to get started with this project. Gitbook is good enough and I like how [fela](http://fela.js.org/) is using it. 

### Tasks

- [x] Create GitHub templates for issues and pull requests.
- [x] Update README.md file to include basic information (getting started).
- [x] Create markdownlint configuration.
- [x] Table Of Contents.
- [x] Publish the docs to gitbook.
